### ISSUE TITLE
Why doesn't the code here match what's on Npm?

### ISSUE THREAD

**Issue by cinderblock** [meszaros-lajos-gyorgy/node-pkware#3]
Looking at https://www.npmjs.com/package/node-pkware, I see a mostly complete README.

Looking here, I see sections to be completed.

Looking at https://unpkg.com/node-pkware@0.8.1/src/implode.mjs, I see that `implode` is implemented (at least partially) but here, it does not seem to be implemented.

Looking deeper, it seems you've moved your original sources to `_old`... are you doing a rewrite or something?

**Comment by meszaros-lajos-gyorgy** [comment]
Hello!
Yes, I'm doing a major rewrite for some time now and I haven't published anything to npm, which wasn't fully finished. I'm ditching the mjs version and going back to cjs until I have a fully working implode and explode implementation and I'm trying to back everything up with unit tests and a lot of test files (moved test files to a separate repository: https://github.com/meszaros-lajos-gyorgy/pkware-test-files).

**Comment by cinderblock** [comment]
Ah. Might I suggest using TypeScript instead? If you're doing a wholesale switch over, might as well get some type safety too :)

**Comment by meszaros-lajos-gyorgy** [comment]
I might look into adding typescript support, but not before shipping version 1.0. I've released a beta version, since explode now works and is stable and has a proper api now with lots of nice helper functions: https://www.npmjs.com/package/node-pkware/v/1.0.0-beta.0

Readme is a bit clumsy at the moment, will clean that up as I go along with the development, but for now please take a look at it and see if it fits your needs.

In the meantime I'll get to working on implode.

**Comment by cinderblock** [comment]
I'm looking forward to the implode, or even just a pkware compatible implode that does the minimum work. I don't actually need to reduce the file size much for my particular application.

**Comment by meszaros-lajos-gyorgy** [comment]
https://github.com/meszaros-lajos-gyorgy/node-pkware/releases/tag/v1.0.0-beta.1 has been released and it supports implode at a basic level without finding repetitions.

**Comment by meszaros-lajos-gyorgy** [comment]
https://github.com/meszaros-lajos-gyorgy/node-pkware/releases/tag/v1.0.0 have been released, which is now a stable release and contains all the goodies from recent versions. It can also finally compress data into something smaller then the input data.
